name: Build and Release
on: 
  push:
    branches:
      - master

jobs:
    build-release:
        name: Build and Release
        runs-on: windows-latest
        permissions:
          contents: write
        steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.1
        - name: Setup Python
          uses: actions/setup-python@v5.1.0
          with:
            python-version-file: '.python-version'
        - name: Install PyInstaller
          run: pip install pyinstaller
        - name: Build release artifact
          run: pyinstaller --onefile .\split_cheats_melonds.py
        - name: Rename exe
          run: Move-Item split_cheats_melonds.exe MelonDSCheatSplitter.exe
        - name: Create release
          uses: softprops/action-gh-release@v2.0.4
          with: 
            token: "${{ secrets.GITHUB_TOKEN }}"
            tag_name: ${{ github.run_number }}
            make_latest: true
            generate_release_notes: true
            files: |
              dist/MelonDSCheatSplitter.exe